---
abstract: 'intersecting lines and circles'
author:
  - 'Lutz Gehlen <perl@lutzgehlen.de>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Geometry-Construction
requires:
  Carp: 0
  LaTeX::TikZ: 0
  List::MoreUtils: 0
  Math::MatrixReal: 0
  Math::VectorReal: 0
  Moose: 0
  Moose::Role: 0
  SVG: 0
  perl: 5.008008
version: 0.008
